[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.forwardedHeaders]
      insecure = true

[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false
