version: '3.8'

services:
  web:
    command: uvicorn main:app --host 0.0.0.0 --port 8081
    build: ./app
    expose:
      - 8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.testlib.com`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8081"
    networks:
      - traefik-network
  traefik:
    build:
      context: traefik
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - "./traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-network

volumes:
  traefik-public-certificates:
networks:
  traefik-network:
    external: true
